### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by drobati** [bjornkri/django-tumblr#1]
You don't have a requirements file or list what is required to use this. Such as the tumblr api module? Where is this? What is this? Is this dependent on certain django version?

**Comment by bjornkri** [comment]
Hi there,  

Sorry, I haven't used or updated this project since January 2009. I'm almost certain whatever answer I would give you would not be very helpful. You'd probably have more luck with one of the forks.

Good luck!

## -Björn

Björn Kristinsson
bjornkri@gmail.com

**Comment by drobati** [comment]
Ah, I didn't look at the date of the last commits.

Cheers,
Derek
